services:
  redis:
    image: 'redis:7.4.2-alpine'
    ports:
      - '6379:6379'
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=ledger_banking_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5434:5432'
    volumes:
        - 'ledger_banking_db_data:/var/lib/postgresql/data'

volumes:
  ledger_banking_db_data: